approvedGitRepositories:
  - "**"

enableGlobalCache: true

enableImmutableInstalls: false

enableScripts: true

installStatePath: .yarn/install-state.gz

nmHoistingLimits: workspaces

nodeLinker: node-modules
