services:
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: strapi
    networks:
      - app
    restart: unless-stopped
    env_file:
      - apps/strapi/.env
      - .env
    volumes:
      - ./apps/strapi/config:/opt/app/config
      - ./apps/strapi/src:/opt/app/src
      - ./apps/strapi/package.json:/opt/app/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./apps/strapi/public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    depends_on:
      - postgres
networks:
  app:
    driver: bridge
volumes:
  postgres:
    name: postgres
    external: true